name: General Issue
description: Click me to open an issue
body:
- type: checkboxes
  attributes:
    label: 'The "I tried" test'
    description: 'Please confirm the following:'
    options:
      - label: I've read the [tutorial](https://github.com/FreshSupaSulley/Auto-2FA/blob/main/TUTORIAL.md) and did my best to understand how this extension works
        required: true