name: Issue Template
description: Want to open an issue?
body:
- type: checkboxes
  attributes:
    label: Dummy test
    description: Uhhh
    options:
      - label: I've read the [tutorial](TUTORIAL.md)
        required: true